### PR TITLE
Deprecate components-examples and components-apidoc

### PR DESCRIPTION
**Pull request by manolo**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-components/4)

### CODE REVIEW

**Comment by tomivirkki** [comment]
<sup>**[README.md, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-components/4#-JzEmIg-KcNpD0MfcJH8)** ([raw file](https://github.com/vaadin/vaadin-components/blob/4a10c10802d6eec581ee02402dc023df0189317c/README.md#L1)):</sup>
Why "Vaadin Component"

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-components/4)

**Comment by tomivirkki** [comment]
<sup>**[demo/index.html, line 51 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-components/4#-JzEoFrgnpYrrMRumZAg)** ([raw file](https://github.com/vaadin/vaadin-components/blob/e20840f4496981c1abfb5eef28620824c59a3b30/demo/index.html#L51)):</sup>
This page doesn't show anything. There's no README.html file in the repo.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-components/4)

**Comment by tomivirkki** [comment]
<sup>**[README.md, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-components/4#-JzEp6joChvLvxWUQlz0)** ([raw file](https://github.com/vaadin/vaadin-components/blob/4a10c10802d6eec581ee02402dc023df0189317c/README.md#L13)):</sup>
These changes would break the main page here http://vaadin.github.io/components-examples/

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-components/4)

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[demo/index.html, line 51 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-components/4#-JzEoFrgnpYrrMRumZAg)** ([raw file](https://github.com/vaadin/vaadin-components/blob/e20840f4496981c1abfb5eef28620824c59a3b30/demo/index.html#L51)):</sup>
It's not in the repo but in the CDN because gulp deploy tasks transforms markdown to html

---

<sup>**[README.md, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-components/4#-JzEmIg-KcNpD0MfcJH8)** ([raw file](https://github.com/vaadin/vaadin-components/blob/4a10c10802d6eec581ee02402dc023df0189317c/README.md#L1)):</sup>
A mistake, fixed

---

<sup>**[README.md, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-components/4#-JzEp6joChvLvxWUQlz0)** ([raw file](https://github.com/vaadin/vaadin-components/blob/4a10c10802d6eec581ee02402dc023df0189317c/README.md#L13)):</sup>
components-examples is deprecated, and should be removed. These changes will never go to components-examples, since this is a different project.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-components/4)

**Comment by tomivirkki** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[demo/index.html, line 51 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-components/4#-JzEoFrgnpYrrMRumZAg)** ([raw file](https://github.com/vaadin/vaadin-components/blob/e20840f4496981c1abfb5eef28620824c59a3b30/demo/index.html#L51)):</sup>
Ah, ok then

---

<sup>**[README.md, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-components/4#-JzEp6joChvLvxWUQlz0)** ([raw file](https://github.com/vaadin/vaadin-components/blob/4a10c10802d6eec581ee02402dc023df0189317c/README.md#L13)):</sup>
Components examples index page reads the file from vaadin-components repository trough github apis. If we merge this now, the site will break. It could be changed to read it from it's own bower_components/vaadin-components until it gets deprecated.

Applying these changes is still problematic because then the links on https://github.com/vaadin/vaadin-components landing page would point to https://github.com/vaadin-grid/demo

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-components/4)

**Comment by jounik** [comment]
Can’t we still keep the URLs absolute like before? Or maybe we need to redesign that section again completely, and have instructions like “do this to run the demos locally, or visit this URL to see them online”.

**Comment by tomivirkki** [comment]
Also, if the markdown file is converted to html anyway during the cdn build process, surely the absolute links could be manipulated there as well (should they be relative in cdn)

**Comment by manolo** [comment]
I would rather relative url's so as we can test cdn in local: `gulp stage:cdn; cd target/cdn; serve`.
Absolute links only would work when running the project in polyserve mode, but I don't think it's a problem since in polyserver means we are developers and we can open README.md in our IDE.
The solution is to get README.md instad of README.html, parse it with marked in JS, and remove the task in gulp.

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[README.md, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-components/4#-JzEp6joChvLvxWUQlz0)** ([raw file](https://github.com/vaadin/vaadin-components/blob/4a10c10802d6eec581ee02402dc023df0189317c/README.md#L13)):</sup>
I see, will think about this, probably we have to modify files during staging

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-components/4)

**Comment by tomivirkki** [comment]
<sup>**[README.md, line 13 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-components/4#-JzQX9n1X9_Tdzc3ePFd)** ([raw file](https://github.com/vaadin/vaadin-components/blob/1943e2c1d4b964e64a572eee2515ae402b1e83c8/README.md#L13)):</sup>
Based on earlier discussion should be ../vaadin-components/latest/...

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-components/4)

**Comment by tomivirkki** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-components/4)

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[README.md, line 13 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-components/4#-JzQX9n1X9_Tdzc3ePFd)** ([raw file](https://github.com/vaadin/vaadin-components/blob/1943e2c1d4b964e64a572eee2515ae402b1e83c8/README.md#L13)):</sup>
It is changed by a gulp task when deployment, otherwise this file would not work when someone visiting github.com/vaadin-components

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-components/4)

**Comment by tomivirkki** [comment]
<sup>**[README.md, line 13 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-components/4#-JzQX9n1X9_Tdzc3ePFd)** ([raw file](https://github.com/vaadin/vaadin-components/blob/1943e2c1d4b964e64a572eee2515ae402b1e83c8/README.md#L13)):</sup>
That was an old comment (17 hours ago), it's fixed already. Now it's the way it's supposed to be

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-components/4)

**Pull request merged**
